### ISSUE TITLE
pagina niet up-to-date

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs.nl-nl#3]
@Kokkie-continues commented on [Fri Jan 25 2019](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/18)

De vertaling voor januari 2019 ontbreekt nog, zie https://docs.microsoft.com/en-us/power-bi/report-server/changelog

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: ef9c2df3-28df-34d8-bd4e-4209996f7f8d
* Version Independent ID: e5dc42c8-b17a-4e0e-09c5-76124b0ad924
* Content: [Wijzigingenlogboek voor Power BI Report Server - Power BI](https://docs.microsoft.com/nl-nl/power-bi/report-server/changelog)
* Content Source: [powerbi-docs/report-server/changelog.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/report-server/changelog.md)
* Service: **powerbi**
* GitHub Login: @jtarquino
* Microsoft Alias: **jtarquino**

---

@CeciAc commented on [Fri Jan 25 2019](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/18#issuecomment-457579070)

Hallo, @Kokkie-continues 
 Hartelijk dank voor uw feedback. 
 We gaan uw opmerkingen bekijken en geven u snel een reactie. 
 Met vriendelijke groet, 
Het team van Microsoft DOCS International

**Comment by LisandroSu** [comment]
Hello, @Kokkie-continues ,

Hartelijk dank   voor uw feedback.

Het document is nu bijgewerkt

We stellen uw   bijdrage aan onze artikelen zeer op prijs en we hopen dat u ons uw   waardevolle feedback zal blijven geven.

Met vriendelijke   groet,
Het team van Microsoft DOCS International
