### ISSUE TITLE
instructie komt niet overeen met werkelijkheid

### ISSUE THREAD

**Issue by mathijsboermans** [MicrosoftDocs/powerbi-docs.nl-nl#5]
Goedenavond,

De instructie zoals hierboven weergegeven komt niet overeen met de werkelijkheid. Ik vermoed dat deze site verouderd is.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 5c4bae6e-72e1-e41c-4419-48a56423e81e
* Version Independent ID: 6d864495-b578-2d28-169d-edb5409de943
* Content: [Een aangepaste visual voor Power BI ontwikkelen - Power BI](https://docs.microsoft.com/nl-nl/power-bi/developer/custom-visual-develop-tutorial#feedback)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @sranins
* Microsoft Alias: **rasala**

**Comment by CeciAc** [comment]
Hallo @mathijsboermans 
We stellen uw opmerking zeer op prijs en willen ons ervoor inzetten om uw ervaring op docs.microsoft.com te verbeteren. We hebben echter meer informatie nodig om uw feedback te kunnen behandelen. Zou u zo vriendelijk willen zijn meer gedetailleerde informatie door te geven en uw opmerking te verduidelijken?
Met vriendelijke groet,
Het internationale team van Microsoft DOCS

**Comment by CeciAc** [comment]
Hallo @mathijsboermans
We geven opvolging aan onze vorige opmerking. We hebben meer informatie nodig om uw feedback te kunnen behandelen. Zou u zo vriendelijk willen zijn meer gedetailleerde informatie door te geven en uw opmerking te verduidelijken?
Met vriendelijke groet,
Het internationale team van Microsoft DOCS

**Comment by CeciAc** [comment]
Hallo @mathijsboermans
Nogmaals dank voor uw opmerking.
Er ontbreekt echter nog steeds informatie waardoor we uw feedback niet kunnen verwerken. Dit GitHub-probleem wordt nu gesloten, maar we moedigen u aan in de toekomst meer feedback te verzenden.
Met vriendelijke groet,
Het internationale team van Microsoft DOCS
